spring:
  config:
    activate:
      on-profile: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:9000/test
    username: admin
    password: comket7791!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    # Show sql when spring data jpa performs query
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Format queries
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  docker:
    compose:
      enabled: false
