springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  profiles:
    active: live # 해당 부분을 local로 설정 시 로컬 환경 적용, live로 설정 시 라이브 서버 환경 적용

--- # 운영 환경에 대한 설정
--- # 라이브 서버 환경에 대한 설정
google:
  oauth2_redirect_uri: http://comket.co.kr/api/v1/auth/oauth2/google/login
  oauth2_client_id: ${GOOGLE_OAUTH2_CLIENT_ID}
  oauth2_client_secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

spring:
  baseurl: "http://comket.co.kr"

  config:
    activate:
      on-profile: live
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://comket-rds.c3mka68c68ht.ap-northeast-2.rds.amazonaws.com:3306/comket
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    # Show sql when spring data jpa performs query
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # Format queries
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: false
jwt:
  secret: ${JWT_SECRET}
